version: "3.7"
services:
  app:
    build:
      args:
        user: sammy
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: spa
    container_name: spa-app
    restart: always
    working_dir: /var/www/
    volumes:
        - ./:/var/www
    networks:
      - spa


  db:
    image: mysql:5.7
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    command: --character-set-server=utf8 --collation-server=utf8_general_ci
    ports:
      - "6033:3306"
    volumes:
      - ./docker-compose/mysql/init:/docker-entrypoint-initdb.d
      - ./docker-compose/mysql/db_data:/var/lib/mysql
    networks:
      - spa

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    links:
      - db
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
      UPLOAD_LIMIT: 300M
    restart: always
    ports:
      - 8081:80
    networks:
      - spa



  nginx:
    image: nginx:alpine
    container_name: spa-nginx
    restart: always
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d/
    networks:
      - spa

networks:
  spa:
    driver: bridge


